In [61]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [63]:
df=pd.read_csv("heart.csv")

In [65]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0


In [74]:
x=df.drop('target',axis=1)
y=df['target']

In [76]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [78]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

## LINEAR SVC/LINEAR KERNEL( accuracy: 81 %)

In [82]:
svc=SVC(kernel='linear')
svc.fit(x_train_scaled,y_train)

SVC(kernel='linear')

In [86]:
y_pred=svc.predict(x_test_scaled)
acc=accuracy_score(y_test,y_pred)

In [90]:
## PERFORMANCE METRICES
print(f"THE ACCURACY:{acc}")
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

THE ACCURACY:0.8146341463414634
[[72 30]
 [ 8 95]]
              precision    recall  f1-score   support

           0       0.90      0.71      0.79       102
           1       0.76      0.92      0.83       103

    accuracy                           0.81       205
   macro avg       0.83      0.81      0.81       205
weighted avg       0.83      0.81      0.81       205



In [128]:
svc.support_vectors_

array([[-0.58584022,  0.65465367,  1.008275  , ...,  1.00526437,
         2.17169136, -0.54519316],
       [ 0.28739583,  0.65465367,  1.008275  , ..., -0.64007851,
         0.24025219,  1.11057867],
       [ 0.50570484, -1.52752523, -0.91672034, ..., -0.64007851,
        -0.7254674 , -0.54519316],
       ...,
       [-1.24076726,  0.65465367, -0.91672034, ...,  1.00526437,
        -0.7254674 , -0.54519316],
       [-1.45907627,  0.65465367,  1.008275  , ..., -0.64007851,
        -0.7254674 , -0.54519316],
       [-1.24076726,  0.65465367, -0.91672034, ...,  1.00526437,
        -0.7254674 ,  1.11057867]])

In [130]:
svc.dual_coef_

array([[-1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -0.41828803, -0.32058647, -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -0.3114062 ,
        -1.        , -1.        , -1.        , -0.10248599, -1.        ,
        -1.        , -1.        , -1.        , -1.        , -0.04996659,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -0.01386819, -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -0.00653212, -1.        , -1.        ,
        -0.02097697, -1.        , -1.        , -1. 

In [132]:
svc.n_support_

array([150, 148], dtype=int32)

## POLYNOMIAL KERNEL( accuracy: 91 %)

In [198]:
poly=SVC(kernel='poly',probability=True)
poly.fit(x_train_scaled,y_train)

SVC(kernel='poly', probability=True)

In [200]:
y_pred=poly.predict(x_test_scaled)
acc=accuracy_score(y_test,y_pred)

In [202]:
## PERFORMANCE METRICES
print(f"THE ACCURACY:{acc}")
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

THE ACCURACY:0.9073170731707317
[[ 85  17]
 [  2 101]]
              precision    recall  f1-score   support

           0       0.98      0.83      0.90       102
           1       0.86      0.98      0.91       103

    accuracy                           0.91       205
   macro avg       0.92      0.91      0.91       205
weighted avg       0.92      0.91      0.91       205



In [204]:
poly.support_vectors_

array([[ 0.28739583,  0.65465367,  1.008275  , ..., -0.64007851,
         0.24025219,  1.11057867],
       [-0.36753121,  0.65465367, -0.91672034, ...,  1.00526437,
        -0.7254674 ,  1.11057867],
       [-1.13161275,  0.65465367, -0.91672034, ...,  1.00526437,
         0.24025219, -0.54519316],
       ...,
       [-1.02245825,  0.65465367,  0.04577733, ...,  1.00526437,
        -0.7254674 , -0.54519316],
       [-1.45907627,  0.65465367,  1.008275  , ..., -0.64007851,
        -0.7254674 , -0.54519316],
       [-1.24076726,  0.65465367, -0.91672034, ...,  1.00526437,
        -0.7254674 ,  1.11057867]])

In [206]:
poly.n_support_

array([160, 164], dtype=int32)

## RBF KERNEL( accuracy: 89 %)

In [209]:
rbf=SVC(kernel='rbf')
rbf.fit(x_train_scaled,y_train)

SVC()

In [211]:
y_pred=rbf.predict(x_test_scaled)
acc=accuracy_score(y_test,y_pred)

In [213]:
## PERFORMANCE METRICES
print(f"THE ACCURACY:{acc}")
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

THE ACCURACY:0.8878048780487805
[[85 17]
 [ 6 97]]
              precision    recall  f1-score   support

           0       0.93      0.83      0.88       102
           1       0.85      0.94      0.89       103

    accuracy                           0.89       205
   macro avg       0.89      0.89      0.89       205
weighted avg       0.89      0.89      0.89       205



In [215]:
rbf.support_vectors_

array([[ 0.28739583,  0.65465367,  1.008275  , ..., -0.64007851,
         0.24025219,  1.11057867],
       [ 0.50570484, -1.52752523, -0.91672034, ..., -0.64007851,
        -0.7254674 , -0.54519316],
       [-1.13161275,  0.65465367, -0.91672034, ...,  1.00526437,
         0.24025219, -0.54519316],
       ...,
       [-1.02245825,  0.65465367,  0.04577733, ...,  1.00526437,
        -0.7254674 , -0.54519316],
       [-1.45907627,  0.65465367,  1.008275  , ..., -0.64007851,
        -0.7254674 , -0.54519316],
       [-1.24076726,  0.65465367, -0.91672034, ...,  1.00526437,
        -0.7254674 ,  1.11057867]])

In [217]:
rbf.n_support_

array([159, 154], dtype=int32)

In [218]:
from sklearn.model_selection import cross_val_score


In [221]:
linear_cv = cross_val_score(svc, x_train_scaled, y_train, cv=5)
rbf_cv = cross_val_score(rbf, x_train_scaled, y_train, cv=5)
poly_cv = cross_val_score(poly, x_train_scaled, y_train, cv=5)

print(linear_cv.mean())
print(rbf_cv.mean())
print(poly_cv.mean())

0.8426829268292682
0.9195121951219513
0.9182926829268293


In [222]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

In [282]:
from sklearn.model_selection import GridSearchCV
param_grid={
    'C':[0.1,1,10,100],
    'degree':[2,3,4,5],
    'gamma':['scale','auto'],
    'coef0':[0,1,10,100]
}
grid=GridSearchCV(estimator=poly,param_grid=param_grid,scoring='accuracy',n_jobs=-1,cv=cv)

In [284]:
grid.fit(x_train_scaled,y_train)


GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=SVC(kernel='poly', probability=True), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10, 100], 'coef0': [0, 1, 10, 100],
                         'degree': [2, 3, 4, 5], 'gamma': ['scale', 'auto']},
             scoring='accuracy')

In [285]:
print(grid.best_params_)
print(grid.best_score_)

{'C': 0.1, 'coef0': 10, 'degree': 5, 'gamma': 'scale'}
0.9853658536585366


In [302]:
best_model=grid.best_estimator_
y_pred = best_model.predict(x_test_scaled)


In [304]:
print("Test Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))

Test Accuracy: 0.9853658536585366
              precision    recall  f1-score   support

           0       0.97      1.00      0.99       102
           1       1.00      0.97      0.99       103

    accuracy                           0.99       205
   macro avg       0.99      0.99      0.99       205
weighted avg       0.99      0.99      0.99       205

[[102   0]
 [  3 100]]


In [300]:
scaler

StandardScaler()

In [298]:
best_model

SVC(C=0.1, coef0=10, degree=5, kernel='poly', probability=True)

In [306]:
import pickle
pickle.dump(scaler,open("scaler.pkl",'wb'))
pickle.dump(best_model,open("new_best_model.pkl",'wb'))

In [308]:
print(type(best_model))
print(best_model.probability)
print(best_model.get_params())

<class 'sklearn.svm._classes.SVC'>
True
{'C': 0.1, 'break_ties': False, 'cache_size': 200, 'class_weight': None, 'coef0': 10, 'decision_function_shape': 'ovr', 'degree': 5, 'gamma': 'scale', 'kernel': 'poly', 'max_iter': -1, 'probability': True, 'random_state': None, 'shrinking': True, 'tol': 0.001, 'verbose': False}
